import React from "react";
import Navbar from "../Home/Navbar";
import Footer from "../Home/Footer";

function Terms() {
  return (
    <div>
    <Navbar/>
      <div class="container mb-8 mt-8">
        <h3>Terms & Conditions</h3>
        <p>Updated at 2023-04-21</p>

        <h4>General Terms</h4>
        <p>
          By accessing and placing an order with FROZENWALA (Sarfaraz), you
          confirm that you are in agreement with and bound by the terms of
          service contained in the Terms & Conditions outlined below. These
          terms apply to the entire website and any email or other type of
          communication between you and FROZENWALA (Sarfaraz). Under no
          circumstances shall FROZENWALA (Sarfaraz) team be liable for any
          direct, indirect, special, incidental, or consequential damages,
          including, but not limited to, loss of data or profit, arising out of
          the use, or the inability to use, the materials on this site, even if
          FROZENWALA (Sarfaraz) team or an authorized representative has been
          advised of the possibility of such damages. If your use of materials
          from this site results in the need for servicing, repair, or
          correction of equipment or data, you assume any costs thereof.
          FROZENWALA (Sarfaraz) will not be responsible for any outcome that may
          occur during the course of usage of our resources. We reserve the
          right to change prices and revise the resources usage policy at any
          moment without any prior intimation / notice.
        </p>

        <h4>License</h4>
        <p>
          FROZENWALA (Sarfaraz) grants you a revocable, non-exclusive,
          non-transferable, limited license to download, install and use the
          website strictly in accordance with the terms of this Agreement. These
          Terms & Conditions are a contract between you and FROZENWALA
          (Sarfaraz) (referred to in these Terms & Conditions as "FROZENWALA
          (Sarfaraz)", "us", "we" or "our"), the provider of the FROZENWALA
          (Sarfaraz) website and the services accessible from the FROZENWALA
          (Sarfaraz) website (which are collectively referred to in these Terms
          & Conditions as the "FROZENWALA (Sarfaraz) Service"). You are agreeing
          to be bound by these Terms & Conditions. If you do not agree to these
          Terms & Conditions, please do not use the FROZENWALA (Sarfaraz)
          Service. In these Terms & Conditions, "you" refers both to you as an
          individual and to the entity you represent. If you violate any of
          these Terms & Conditions, we reserve the right to cancel your account
          or block access to your account without notice.
        </p>

        <h4>Definitions and key terms</h4>
        <p>
          To help explain things as clearly as possible in this Terms &
          Conditions, every time any of these terms are referenced, are strictly
          defined as:
        </p>

        <h5>Cookie:</h5>
        <p>
          {" "}
          small amount of data generated by a website and saved by your web
          browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </p>

        <h5>Company:</h5>
        <p>
          when these terms mention “Company,” “we,” “us,” or “our,” it refers to
          FROZENWALA (Sarfaraz), that is responsible for your information under
          this Terms & Conditions.
        </p>

        <h5>Country:</h5>
        <p>
          where FROZENWALA (Sarfaraz) or the owners/founders of FROZENWALA
          (Sarfaraz) are based, in this case is India.
        </p>

        <h5>Device:</h5>
        <p>
          {" "}
          any internet-connected device such as a phone, tablet, computer, or
          any other device that can be used to visit FROZENWALA (Sarfaraz) and
          use the services.
        </p>

        <h5>Service:</h5>
        <p>
          refers to the service provided by FROZENWALA (Sarfaraz) as described
          in the relative terms (if available) and on this platform.
        </p>

        <h5>Third-party service:</h5>
        <p>
          refers to advertisers, contest sponsors, promotional and marketing
          partners, and others who provide our content or whose products or
          services we think may interest you.
        </p>

        <h5>Website:</h5>
        <p>
          FROZENWALA (Sarfaraz)’s site, which can be accessed via this :
          https://frozenwala.live
        </p>

        <h5>You:</h5>
        <p>
          a person or entity that is registered with FROZENWALA (Sarfaraz) to
          use the Services.
        </p>

        <h4>Restrictions</h4>
        <p>
          You agree not to, and you will not permit others to: a) License, sell,
          rent, lease, assign, distribute, transmit, host, outsource, disclose
          or otherwise commercially exploit the website or make the platform
          available to any third party. b) Modify, make derivative works of,
          disassemble, decrypt, reverse compile or reverse engineer any part of
          the website. c) Remove, alter or obscure any proprietary notice
          (including any notice of copyright or trademark) of FROZENWALA
          (Sarfaraz) or its affiliates, partners, suppliers or the licensors of
          the website.
        </p>

        <h4>Payment</h4>
        <p>
          If you pay for any of our one-time payment plans, you agree to pay all
          fees or charges to your account for the Service in accordance with the
          fees, charges, and billing terms in effect at the time that each fee
          or charge is due and payable. Your Payment Provider agreement governs
          your use of the designated credit card account, and you must refer to
          that agreement and not these Terms to determine your rights and
          liabilities with respect to your Payment Provider. By providing
          FROZENWALA (Sarfaraz) with your credit card number and associated
          payment information, you agree that FROZENWALA (Sarfaraz) is
          authorized to verify information immediately, and subsequently invoice
          your account for all fees and charges due and payable to FROZENWALA
          (Sarfaraz) hereunder and that no additional notice or consent is
          required. You agree to immediately notify FROZENWALA (Sarfaraz) of any
          change in your billing address or the credit card or payment mode used
          for payment hereunder. FROZENWALA (Sarfaraz) reserves the right at any
          time to change its prices and billing methods, either immediately upon
          posting on our Site or by e-mail delivery to your organization’s
          administrator(s). Any attorney fees, court costs, or other costs
          incurred in the collection of delinquent undisputed amounts shall be
          the responsibility of and paid for by you. No contract will exist
          between you and FROZENWALA (Sarfaraz) for the Service until FROZENWALA
          (Sarfaraz) accepts your order by a confirmatory e-mail, SMS/MMS
          message, or other appropriate means of communication. You are
          responsible for any third-party fees that you may incur when using the
          Service.
        </p>
        <h4>Your Suggestions</h4>
        <p>
          Any feedback, comments, ideas, improvements or suggestions
          (collectively, "Suggestions") provided by you to FROZENWALA (Sarfaraz)
          with respect to the website shall remain the sole and exclusive
          property of FROZENWALA (Sarfaraz). FROZENWALA (Sarfaraz) shall be free
          to use, copy, modify, publish, or redistribute the Suggestions for any
          purpose and in any way without any credit or any compensation to you.
        </p>

        <h4>Your Consent</h4>
        <p>
          We've updated our Terms & Conditions to provide you with complete
          transparency into what is being set when you visit our site and how
          it's being used. By using our website, registering an account, or
          making a purchase, you hereby consent to our Terms & Conditions.
        </p>

        <h4>Links to Other Websites</h4>
        <p>
          These Terms & Conditions apply only to the Services provided on our
          Website. The Services may contain links to other websites not operated
          or controlled by FROZENWALA (Sarfaraz). We are not responsible for the
          content, accuracy, or opinions expressed in such websites, and such
          websites are not investigated, monitored, or checked for accuracy or
          completeness by us. Please remember that when you use a link to go
          from the Services to another website, our Terms & Conditions are no
          longer in effect. Your browsing and interaction on any other website,
          including those that have a link on our platform, is subject to that
          website’s own rules and policies. Such third parties may use their own
          cookies or other methods to collect information about you.
        </p>

        <h4>Cookies</h4>
        <p>
          FROZENWALA (Sarfaraz) uses "Cookies" to identify the areas of our
          website that you have visited. A cookie is a small piece of data
          stored on your computer or mobile device by your web browser. We use
          cookies to enhance the performance and functionality of our website
          but are non-essential to their use. However, without these cookies,
          certain functionality like videos may become unavailable or you would
          be required to enter your login details every time you visit the
          website as we would not be able to remember that you had logged in
          previously. Most web browsers can be set to disable the use of
          Cookies. However, if you disable Cookies, you may not be able to
          access functionality on our website correctly or at all. We never
          place Personally Identifiable Information in Cookies.
        </p>

        <h4>Modifications to Our website</h4>
        <p>
          FROZENWALA (Sarfaraz) solely reserves the right to modify, suspend or
          discontinue, temporarily or permanently, the website or any service to
          which it connects, with or without notice and without liability to
          you.
        </p>

        <h4>Updates to Our website</h4>
        <p>
          FROZENWALA (Sarfaraz) may from time to time provide enhancements or
          improvements to the features/ functionality of the wWebsite, which may
          include patches, bug fixes, updates, upgrades and other modifications
          ("Updates"). Updates may modify or delete certain features and/or
          functionalities of the website. You agree that FROZENWALA (Sarfaraz)
          has no obligation to (i) provide any Updates, or (ii) continue to
          provide or enable any particular features and/or functionalities of
          the website to you. You further agree that all Updates will be (i)
          deemed to constitute an integral part of the website, and (ii) subject
          to the terms and conditions of this Agreement.
        </p>

        <h4>Third-Party Services</h4>
        <p>
          We may display, include or make available third-party content
          (including data, information, applications, and other products
          services) or provide links to third-party websites or services
          ("Third-Party Services"). You acknowledge and agree that FROZENWALA
          (Sarfaraz) shall not be responsible for any Third-Party Services,
          including their accuracy, completeness, timeliness, validity,
          copyright compliance, legality, decency, quality, or any other aspect
          thereof. FROZENWALA (Sarfaraz) does not assume and shall not have any
          liability or responsibility to you or any other person or entity for
          any Third-Party Services. Third-Party Services and links thereto are
          provided solely as a convenience to you and you access and use them
          entirely at your own risk and subject to such third parties terms and
          conditions.
        </p>

        <h4>Term and Termination</h4>
        <p>
          This Agreement shall remain in effect until terminated by you or
          FROZENWALA (Sarfaraz). FROZENWALA (Sarfaraz) may, in its sole
          discretion, at any time and for any or no reason, suspend or terminate
          this Agreement with or without prior notice. This Agreement will
          terminate immediately, without prior notice from FROZENWALA
          (Sarfaraz), in the event that you fail to comply with any provision of
          this Agreement. You may also terminate this Agreement by deleting the
          website and all copies thereof from your computer. Upon termination of
          this Agreement, you shall cease all use of the wWebsite and delete all
          copies of the website from your computer. Termination of this
          Agreement will not limit any of FROZENWALA (Sarfaraz)'s rights or
          remedies at law or in equity in case of breach by you (during the term
          of this Agreement) of any of your obligations under the present
          Agreement.
        </p>

        <h4>Copyright Infringement Notice</h4>
        <p>
          If you are a copyright owner or such owner’s agent and believe any
          material on our Website constitutes an infringement on your copyright,
          please contact us setting forth the following information: (a) a
          physical or electronic signature of the copyright owner or a person
          authorized to act on his behalf; (b) identification of the material
          that is claimed to be infringing; (c) your contact information,
          including your address, telephone number, and an email; (d) a
          statement by you that you have a good faith belief that use of the
          material is not authorized by the copyright owners; and (e) the
          statement that the information in the notification is accurate, and,
          under penalty of perjury you are authorized to act on behalf of the
          owner.
        </p>

        <h4>Indemnification</h4>
        <p>
          You agree to indemnify and hold FROZENWALA (Sarfaraz) and its parents,
          subsidiaries, affiliates, officers, employees, agents, partners, and
          licensors (if any) harmless from any claim or demand, including
          reasonable attorneys' fees, due to or arising out of your: (a) use of
          the website; (b) violation of this Agreement or any law or regulation;
          or (c) violation of any right of a third party.
        </p>

        <h4>No Warranties</h4>
        <p>
          The Website is provided to you "AS IS" and "AS AVAILABLE" and without
          warranty of any kind. To the maximum extent permitted under applicable
          law, FROZENWALA (Sarfaraz), on its own behalf and on behalf of its
          affiliates and its and their respective licensors and service
          providers, expressly disclaims all warranties, whether express,
          implied, statutory, or otherwise, with respect to the wWebsite,
          including all implied warranties of merchantability, fitness for a
          particular purpose, title and non-infringement, and warranties that
          may arise out of a course of dealing, course of performance, usage or
          trade practice. Without limitation to the foregoing, FROZENWALA
          (Sarfaraz) provides no warranty or undertaking, and makes no
          representation of any kind that the website will meet your
          requirements, achieve any intended results, be compatible or work with
          any other software, websites, systems or services, operate without
          interruption, meet any performance or reliability standards or be
          error-free or that any errors or defects can or will be corrected.
          Without limiting the foregoing, neither FROZENWALA (Sarfaraz) nor any
          FROZENWALA (Sarfaraz)'s service provider makes any representation or
          warranty of any kind, express or implied: (i) as to the operation or
          availability of the wWebsite, or the information, content, and
          materials or products included thereon; (ii) that the wWebsite will be
          uninterrupted or error-free; (iii) as to the accuracy, reliability, or
          currency of any information or content provided through the wWebsite;
          or (iv) that the wWebsite, its servers, the content, or e-mails sent
          from or on behalf of FROZENWALA (Sarfaraz) are free of viruses,
          scripts, trojan horses, worms, malware, timebombs or other harmful
          components.
        </p>

        <h4>Limitation of Liability</h4>
        <p>
          Notwithstanding any damages that you might incur, the entire liability
          of FROZENWALA (Sarfaraz) and any of its suppliers under any provision
          of this Agreement and your exclusive remedy for all of the foregoing
          shall be limited to the amount actually paid by you onfor the Website.
          To the maximum extent permitted by applicable law, in no event shall
          FROZENWALA (Sarfaraz) or its suppliers be liable for any special,
          incidental, indirect, or consequential damages whatsoever (including,
          but not limited to, damages for loss of profits, for loss of data or
          other information, for business interruption, for personal injury, for
          loss of privacy arising out of or in any way related to the use of or
          inability to use the Website, third-party software and/or third-party
          hardware used with the wWebsite, or otherwise in connection with any
          provision of this Agreement), even if FROZENWALA (Sarfaraz) or any
          supplier has been advised of the possibility of such damages and even
          if the remedy fails of its essential purpose.
        </p>

        <h4>Severability</h4>
        <p>
          If any provision of this Agreement is held to be unenforceable or
          invalid, such provision will be changed and interpreted to accomplish
          the objectives of such provision to the greatest extent possible under
          applicable law and the remaining provisions will continue in full
          force and effect. This Agreement, together with the Privacy Policy and
          any other policies published by FROZENWALA (Sarfaraz) on the
          Sservices, shall constitute the entire agreement between you and
          FROZENWALA (Sarfaraz) concerning the Sservices. If any provision of
          this Agreement is deemed invalid by a court of competent jurisdiction,
          the invalidity of such provision shall not affect the validity of the
          remaining provisions of this Agreement, which shall remain in full
          force and effect. No waiver of any term of this Agreement shall be
          deemed a further or continuing waiver of such term or any other term,
          and FROZENWALA (Sarfaraz)’s failure to assert any right or provision
          under this Agreement shall not constitute a waiver of such right or
          provision. YOU AND FROZENWALA (Sarfaraz) AGREE THAT ANY CAUSE OF
          ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN
          ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE
          OF ACTION IS PERMANENTLY BARRED.
        </p>

        <h4>Waiver</h4>
        <p>
          Except as provided herein, the failure to exercise a right or to
          require performance of an obligation under this Agreement shall not
          affect a party's ability to exercise such right or require such
          performance at any time thereafter nor shall be the waiver of a breach
          constitute waiver of any subsequent breach. No failure to exercise and
          no delay in exercising, on the part of either party, any right or any
          power under this Agreement shall operate as a waiver of that right or
          power. Nor shall any single or partial exercise of any right or power
          under this Agreement preclude further exercise of that or any other
          right granted herein. In the event of a conflict between this
          Agreement and any applicable purchase or other terms, the terms of
          this Agreement shall govern and supersede any such terms.
        </p>

        <h4>Amendments to this Agreement</h4>
        <p>
          FROZENWALA (Sarfaraz) reserves the right, at its sole discretion, to
          modify or replace this Agreement at any time without any prior notice
          / intimation. Hence we request you to check this Agreement from time
          to time By continuing to access or use our website after any revisions
          become effective, it shall be deemed that youyou agree to be bound by
          the revised terms. If you do not agree to the new terms, you are no
          longer authorized to use FROZENWALA (Sarfaraz).
        </p>

        <h4>Entire Agreement</h4>
        <p>
          The Agreement constitutes the entire agreement between you and
          FROZENWALA (Sarfaraz) regarding your use of the Website and supersedes
          all prior and contemporaneous written or oral agreements between you
          and FROZENWALA (Sarfaraz). You may be subject to additional terms and
          conditions that apply when you use or purchase other FROZENWALA
          (Sarfaraz)'s services, which FROZENWALA (Sarfaraz) will provide to you
          at the time of such use or purchase.
        </p>

        <h4>Intellectual Property</h4>
        <p>
          The Website and its entire contents, features, and functionality
          (including but not limited to all information, software, text,
          displays, images, video and audio, and the design, selection, and
          arrangement thereof), are owned by FROZENWALA (Sarfaraz), its
          licensors or other providers of such material and are protected by
          India and international copyright, trademark, patent, trade secret and
          other intellectual property or proprietary rights laws. The material
          may not be copied, modified, reproduced, downloaded or distributed in
          any way, in whole or in part, without the express prior written
          permission of FROZENWALA (Sarfaraz), unless and except as is expressly
          provided in these Terms & Conditions. Any unauthorized use of the
          material is prohibited.
        </p>

        <h4>Choice of Law and Venue</h4>
        <p>
          The Terms of Use and policies shall be expounded and construed with
          and by the laws of the India, regardless of its conflict to laws and
          rules in India. Disputes of any sort will be subject to the exclusive
          jurisdiction of the courts situated within New Delhi and the user
          hereby will have to comply with the jurisdiction of the courts of
          Delhi.
        </p>

        <h4>Submissions and Privacy</h4>
        <p>
          In the event that you submit or post any ideas, creative suggestions,
          designs, photographs, information, advertisements, data, or proposals,
          including ideas for new or improved products, services, features,
          technologies, or promotions, you expressly agree that such submissions
          will automatically be treated as non-confidential and non-proprietary
          and will become the sole property of FROZENWALA (Sarfaraz) without any
          compensation or credit to you whatsoever. FROZENWALA (Sarfaraz) and
          its affiliates shall have no obligations with respect to such
          submissions or posts and may use the ideas contained in such
          submissions or posts for any purposes in any medium in perpetuity,
          including, but not limited to, developing manufacturing, and marketing
          products and services using such ideas.
        </p>

        <h4>Promotions</h4>
        <p>
          FROZENWALA (Sarfaraz) may, from time to time, include contests,
          promotions, sweepstakes, or other activities (“Promotions”) that
          require you to submit material or information concerning yourself.
          Please note that all Promotions may be governed by separate rules that
          may contain certain eligibility requirements, such as restrictions as
          to age and geographic location. You are responsible to read all
          Promotions rules to determine whether or not you are eligible to
          participate. If you enter any Promotion, you agree to abide by and to
          comply with all Promotions Rules. Additional terms and conditions may
          apply to purchases of goods or services on or through the Services,
          which terms and conditions are made a part of this Agreement by this
          reference.
        </p>

        <h4>Typographical Errors</h4>
        <p>
          In the event a product and/or service is listed at an incorrect price
          or with incorrect information due to typographical error, we shall
          have the right to refuse or cancel any orders placed for the product
          and/or service listed at the incorrect price. We shall have the right
          to refuse or cancel any such order whether or not the order has been
          confirmed and your credit card charged. If your credit card has
          already been charged for the purchase and your order is canceled, we
          shall immediately issue a credit to your credit card account or other
          payment accounts in the amount of the charge.
        </p>

        <h4>Miscellaneous</h4>
        <p>
          Any waiver of any provision of these Terms & Conditions will be
          effective only if in writing and signed by an authorized
          representative of FROZENWALA (Sarfaraz). FROZENWALA (Sarfaraz) will be
          entitled to injunctive or other equitable relief (without the
          obligations of posting any bond or surety) in the event of any breach
          or anticipatory breach by you. FROZENWALA (Sarfaraz) operates and
          controls the FROZENWALA (Sarfaraz) Service from its offices in India.
          The Service is not intended for distribution to or use by any person
          or entity in any jurisdiction or country where such distribution or
          use would be contrary to law or regulation. Accordingly, those persons
          who choose to access the FROZENWALA (Sarfaraz) Service from other
          locations do so on their own initiative and are solely responsible for
          compliance with local laws, if and to the extent local laws are
          applicable. These Terms & Conditions (which include and incorporate
          the FROZENWALA (Sarfaraz) Privacy Policy) contains the entire
          understanding, and supersedes all prior understandings, between you
          and FROZENWALA (Sarfaraz) concerning its subject matter, and cannot be
          changed or modified by you. The section headings used in this
          Agreement are for convenience only and will not be given any legal
          import.
        </p>

        <h4>Disclaimer</h4>
        <p>
          FROZENWALA (Sarfaraz) is not responsible for any content, code or any
          other imprecision. FROZENWALA (Sarfaraz) does not provide warranties
          or guarantees. In no event shall FROZENWALA (Sarfaraz) be liable for
          any special, direct, indirect, consequential, or incidental damages or
          any damages whatsoever, whether in an action of contract, negligence
          or other torts, arising out of or in connection with the use of the
          Service or the contents of the Service. The Company reserves the right
          to make additions, deletions, or modifications to the contents of the
          Service at any time without prior notice. The FROZENWALA (Sarfaraz)
          Service and its contents are provided "as is" and "as available"
          without any warranty or representations of any kind, whether express
          or implied. FROZENWALA (Sarfaraz) is a distributor and not a publisher
          of the content supplied by third parties; as such, FROZENWALA
          (Sarfaraz) exercises no editorial control over such content and makes
          no warranty or representation as to the accuracy, reliability, or
          currency of any information, content, service or merchandise provided
          through or accessible via the FROZENWALA (Sarfaraz) Service. Without
          limiting the foregoing, FROZENWALA (Sarfaraz) specifically disclaims
          all warranties and representations in any content transmitted on or in
          connection with the FROZENWALA (Sarfaraz) Service or on sites that may
          appear as links on the FROZENWALA (Sarfaraz) Service, or in the
          products provided as a part of, or otherwise in connection with, the
          FROZENWALA (Sarfaraz) Service, including without limitation any
          warranties of merchantability, fitness for a particular purpose or
          non-infringement of third party rights. No oral advice or written
          information was given by FROZENWALA (Sarfaraz) or any of its
          affiliates, employees, officers, directors, agents, or the like will
          create a warranty. Price and availability information is subject to
          change without notice. Without limiting the foregoing, FROZENWALA
          (Sarfaraz) does not warrant that the FROZENWALA (Sarfaraz) Service
          will be uninterrupted, uncorrupted, timely, or error-free.
        </p>

        <h4>Contact Us</h4>
        <p>
          Don't hesitate to contact us if you have any questions. Via Email:
          frozenwalaenterprises@gmail.com Via Phone Number: 8268888826
        </p>
      </div>
      <Footer/>
    </div>
  );
}

export default Terms;
